# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2023-01-05T19:20:53+00:00

from __future__ import annotations

from typing import Any
from typing import Optional

from pydantic import BaseModel


class Category(BaseModel):
    url: str
    name: str
    image: Any
    level_description: str


class Manufacturer(BaseModel):
    url: str
    company_name: str


class ProductList(BaseModel):
    url: str
    name: str
    name_fr: Any
    model: str
    mpn: str
    price: float
    cost: float
    weight: float
    description: str
    description_fr: Any
    status: Any
    category: Category
    manufacturer: Manufacturer
    image: Any
