# generated by datamodel-codegen:
#   filename:  <stdin>
#   timestamp: 2023-01-05T19:37:18+00:00

from __future__ import annotations

from typing import Any
from typing import List
from typing import Optional

from pydantic import BaseModel


class CategoryList(BaseModel):
    name: str
    ancestors: str
    url: str
    name_fr: str
    description: str
    description_fr: str
    parent: Any
    nav_bar: Any
    status: Any
    outside_paint: bool
    cnc: bool
    option_grp: List
    image: Any
    created_at: str
    updated_at: str
    categories: List[str]
    model_name: str
    overlapable: bool
    stackable: bool
    stackontop: bool
    level_description: str
